version: "3"

services: 
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /home/node/app
    command: ['npm','run','serve']
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/home/node/app
    expose: 
      - "8080"

  nginx:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /home/node/app 
    restart: unless-stopped
    volumes:
      - ./app:/home/node/app
    ports:
      - "80:80"
